// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeEbJzRnXzY7HQcfUZnh4z4DIh4OjpYYM',
    appId: '1:1087795509186:web:f34f2409c44e48722ec85b',
    messagingSenderId: '1087795509186',
    projectId: 'flutter-projects-581c8',
    authDomain: 'flutter-projects-581c8.firebaseapp.com',
    storageBucket: 'flutter-projects-581c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrVj4ZC-7wsTtkL-F0-VxBZkMh36SI_GM',
    appId: '1:1087795509186:android:e86cd0f38eb3470b2ec85b',
    messagingSenderId: '1087795509186',
    projectId: 'flutter-projects-581c8',
    storageBucket: 'flutter-projects-581c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt4zqvQAk4hqlIwwKW10Z0HRT_to1HGZE',
    appId: '1:1087795509186:ios:88ae54effeb0227a2ec85b',
    messagingSenderId: '1087795509186',
    projectId: 'flutter-projects-581c8',
    storageBucket: 'flutter-projects-581c8.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt4zqvQAk4hqlIwwKW10Z0HRT_to1HGZE',
    appId: '1:1087795509186:ios:2bced7721e20f6a62ec85b',
    messagingSenderId: '1087795509186',
    projectId: 'flutter-projects-581c8',
    storageBucket: 'flutter-projects-581c8.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
